name: unit

on:
  push:
    branches: [main]
    paths:
      - "sdks/python/**"
      - ".github/workflows/unit-python-sdk.yml"
  pull_request:
    branches: [main]
    paths:
      - "sdks/python/**"
      - ".github/workflows/unit-python-sdk.yml"

jobs:
  python:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          version: ">=0.8.0"

      - name: Load cached venv
        id: cached-uv-dependencies
        uses: actions/cache@v4
        with:
          path: sdks/python/.venv
          key: venv-${{ runner.os }}-${{ hashFiles('sdks/python/uv.lock') }}

      - name: Install dependencies
        working-directory: sdks/python
        run: uv sync

      - name: Run tests
        working-directory: sdks/python
        run: uv run python -m unittest discover tests -v
